// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJJu73BQ896yEIAeneTkRr3pYS8fYzso',
    appId: '1:1022000369604:web:c1ceee30ea3e9b5105de91',
    messagingSenderId: '1022000369604',
    projectId: 'fir-user-app-d57b8',
    authDomain: 'fir-user-app-d57b8.firebaseapp.com',
    storageBucket: 'fir-user-app-d57b8.firebasestorage.app',
    measurementId: 'G-VGJ09F6KVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qlWTTFZNbquleZtNM7W7f_vgZWMcf-o',
    appId: '1:1022000369604:android:6437f9c565e44fd805de91',
    messagingSenderId: '1022000369604',
    projectId: 'fir-user-app-d57b8',
    storageBucket: 'fir-user-app-d57b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKfxeHeY6TY81sMsyk2-DjmZwmvQiBV0',
    appId: '1:1022000369604:ios:25c174d0d6ef865205de91',
    messagingSenderId: '1022000369604',
    projectId: 'fir-user-app-d57b8',
    storageBucket: 'fir-user-app-d57b8.firebasestorage.app',
    iosBundleId: 'com.example.demoProjectUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuKfxeHeY6TY81sMsyk2-DjmZwmvQiBV0',
    appId: '1:1022000369604:ios:25c174d0d6ef865205de91',
    messagingSenderId: '1022000369604',
    projectId: 'fir-user-app-d57b8',
    storageBucket: 'fir-user-app-d57b8.firebasestorage.app',
    iosBundleId: 'com.example.demoProjectUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJJu73BQ896yEIAeneTkRr3pYS8fYzso',
    appId: '1:1022000369604:web:e26de98fcef8e9e905de91',
    messagingSenderId: '1022000369604',
    projectId: 'fir-user-app-d57b8',
    authDomain: 'fir-user-app-d57b8.firebaseapp.com',
    storageBucket: 'fir-user-app-d57b8.firebasestorage.app',
    measurementId: 'G-6GR6Y8YFXR',
  );
}
